import React, { useState } from 'react';
import { BriefData } from '../types';
import { 
  CheckCircle2, AlertTriangle, Target, Users, Code, 
  MessageSquare, HelpCircle, ListTodo, ShieldAlert, 
  Lightbulb, FileText, Send, Copy, Check
} from 'lucide-react';

interface BriefResultProps {
  data: Partial<BriefData>;
}

export const BriefResult: React.FC<BriefResultProps> = ({ data }) => {
  const [copied, setCopied] = useState(false);

  if (!data.summary) return null;

  const handleCopyMarkdown = () => {
    const md = `
# AI BRIEF: ${data.summary || 'Untitled Project'}

## 🎯 Goal
${data.goal}

## ⚠️ Business Problem
${data.businessProblem}

## 👥 Target User
${data.targetUser}

## 💡 Proposed Solution
${data.proposedSolution}

## 🛠 MVP Scope
${data.mvpScope?.map(s => `- ${s}`).join('\n')}

## ❓ Clarifying Questions
${data.clarifyingQuestions?.map(q => `- ${q}`).join('\n')}

## 🏗 Technical Approach
${data.technicalApproach}

---
*Generated by AI Brief Builder*
    `.trim();

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const Section = ({ title, icon: Icon, children, className = "" }: any) => (
    <section className={`bg-white p-6 rounded-2xl shadow-sm border border-black/5 ${className}`}>
      <h3 className="text-lg font-bold text-zinc-900 mb-4 flex items-center gap-2">
        <Icon className="w-5 h-5 text-indigo-600" />
        {title}
      </h3>
      <div className="text-zinc-600 leading-relaxed text-sm">
        {children}
      </div>
    </section>
  );

  const List = ({ items }: { items?: string[] }) => (
    <ul className="space-y-2">
      {items?.map((item, i) => (
        <li key={i} className="flex gap-2 items-start">
          <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-indigo-400 shrink-0" />
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-xl font-black text-zinc-900 uppercase tracking-widest flex items-center gap-2">
          <div className="w-1.5 h-6 bg-indigo-600 rounded-full" />
          Analysis Result
        </h2>
        <button
          onClick={handleCopyMarkdown}
          className={`flex items-center gap-2 px-5 py-2.5 rounded-full text-[10px] font-bold uppercase tracking-widest transition-all shadow-sm ${
            copied 
              ? 'bg-emerald-500 text-white shadow-emerald-100' 
              : 'bg-white text-zinc-600 border border-zinc-200 hover:border-indigo-600 hover:text-indigo-600'
          }`}
        >
          {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
          {copied ? 'Copied' : 'Copy as Markdown'}
        </button>
      </div>

      {/* Primary Summary */}
      <Section title="Summary" icon={Target} className="border-l-4 border-l-indigo-600">
        <p className="text-lg text-zinc-800 font-medium">{data.summary}</p>
      </Section>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Section title="Business Problem" icon={AlertTriangle}>
          {data.businessProblem}
        </Section>
        <Section title="Goal" icon={CheckCircle2}>
          {data.goal}
        </Section>
        <Section title="Target User" icon={Users}>
          {data.targetUser}
        </Section>
        <Section title="Proposed Solution" icon={Lightbulb}>
          {data.proposedSolution}
        </Section>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Section title="MVP Scope" icon={ListTodo}>
          <List items={data.mvpScope} />
        </Section>
        <Section title="Out of Scope" icon={ShieldAlert}>
          <List items={data.outOfScope} />
        </Section>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Section title="Risks" icon={ShieldAlert}>
          <List items={data.risks} />
        </Section>
        <Section title="Assumptions" icon={FileText}>
          <List items={data.assumptions} />
        </Section>
      </div>

      <Section title="Clarifying Questions" icon={HelpCircle}>
        <List items={data.clarifyingQuestions} />
      </Section>

      <Section title="Technical Approach" icon={Code}>
        <div className="bg-zinc-50 p-4 rounded-xl font-mono text-xs border border-zinc-100">
          {data.technicalApproach}
        </div>
      </Section>

      <Section title="Task Draft (Jira/Linear)" icon={FileText}>
        <div className="bg-zinc-900 text-zinc-300 p-4 rounded-xl font-mono text-xs overflow-x-auto">
          <pre className="whitespace-pre-wrap">{data.taskDraft}</pre>
        </div>
      </Section>

      <Section title="Stakeholder Reply" icon={Send} className="bg-indigo-50 border-indigo-100">
        <div className="italic text-indigo-900 bg-white/50 p-4 rounded-xl border border-indigo-100">
          {data.stakeholderReply}
        </div>
      </Section>
    </div>
  );
};
